ci: replace flatpak-builder by org.flatpak.Builder
The latter is now requiring mandatory generation of a .Sources package
for build reproducibility on x86_64 (via the --bundle-sources option),
but that's currently not working well for us:

=====
$ dbus-run-session flatpak run org.flatpak.Builder --arch x86_64 --finish-only \
    --repo repo/ --verbose   builddir/ io.github.horsicq.detect-it-easy.yaml
[...]
Bundling sources
builder_source_git_bundle https://github.com/horsicq/DIE-engine.git
FB: Running: git init --bare /home/runner/work/flatpak-app-detect-it-easy/flatpak-app-detect-it-easy/.flatpak-builder/rofiles/rofiles-7nEt28/sources/git/https_github.com_horsicq_DIE-engine.git
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
hint:
hint: Disable this message with "git config set advice.defaultBranchName false"
Initialized empty Git repository in /home/runner/work/flatpak-app-detect-it-easy/flatpak-app-detect-it-easy/.flatpak-builder/rofiles/rofiles-7nEt28/sources/git/https_github.com_horsicq_DIE-engine.git/
FB: Running: git remote add --mirror=fetch origin /home/runner/work/flatpak-app-detect-it-easy/flatpak-app-detect-it-easy/.flatpak-builder/git/https_github.com_horsicq_DIE-engine.git
FB: Running: git rev-parse --symbolic-full-name
FB: Running: git update-ref 'refs/heads/flatpak-builder-internal/commit/(null)' '(null)^{}'
fatal: (null)^{}: not a valid SHA1
Error: module detect-it-easy: Child process exited with code 128
FB: Unmounting read-only fs: fusermount -uz /home/runner/work/flatpak-app-detect-it-easy/flatpak-app-detect-it-easy/.flatpak-builder/rofiles/rofiles-7nEt28
=====

So let's just use flatpak-builder where we can skip this step.